language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - 2.2.2

gemfile:
  - gemfiles/ruby-1.8.7.gemfile
  - gemfiles/rails_3-1-stable.gemfile
  - gemfiles/rails_3-2-stable.gemfile
  - gemfiles/rails_4-0-stable.gemfile
  - gemfiles/rails_4-1-stable.gemfile
  - gemfiles/rails_4-2-stable.gemfile

env:
  - "CATCH_ALL_ROUTE=true"
  - "DB=mysql"
  - "DB=postgresql"
  - "DB=sqlite"

before_script:
  - mysql -e 'create database rails_db_info_test;'
  - psql -c 'create database rails_db_info_test;' -U postgres

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake

matrix:
  exclude:
    - rvm: 1.8.7
    - rvm: 1.9.3
    - gemfile: gemfiles/ruby-1.8.7.gemfile

  include:
    - rvm: 1.8.7
      gemfile: gemfiles/ruby-1.8.7.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_4-2-stable.gemfile
