language: ruby
rvm:
  - 1.9.3
  - 2.0.0

env:
  - "DB=mysql"
  - "DB=postgresql"
  - "DB=sqlite"
  - "RAILS_VERSION=3.1.0"
  - "RAILS_VERSION=3.2.0"
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=master"

before_script:
  - mysql -e 'create database rails_db_info_test;'
  - psql -c 'create database rails_db_info_test;' -U postgres

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake
